"""create is_read is_file in Message model

Revision ID: 95583e92b205
Revises: 96e8d3755e3d
Create Date: 2025-09-12 14:03:04.323831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95583e92b205'
down_revision: Union[str, Sequence[str], None] = '96e8d3755e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('is_file', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_file')
    op.drop_column('messages', 'is_read')
    # ### end Alembic commands ###
