"""update is_read is_file in Message model and add in Message model column file_url

Revision ID: da6c510a751b
Revises: 95583e92b205
Create Date: 2025-09-12 15:22:27.077083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6c510a751b'
down_revision: Union[str, Sequence[str], None] = '95583e92b205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'file_url')
    # ### end Alembic commands ###
